- name: Install misc packages
  apt:
    name:
      - ruby-full
      - nginx
      - supervisor

- name: Create directories and set permissions
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "/{{ organization_slug }}"
      mode: '2775'
      owner: "root"
    - path: "/{{ organization_slug }}/{{ project_slug }}"
      mode: '2775'
      owner: "{{ main_user }}"
    - path: "/etc/{{ organization_slug }}"
      mode: '2775'
      owner: "root"
    - path: "/etc/{{ organization_slug }}/{{ project_slug }}"
      mode: '2775'
      owner: "{{ main_user }}"
    - path: "{{ var_log_path }}"
      mode: '2770'
      owner: "{{ main_user }}"
    - path: "{{ venv.path }}"
      mode: '0755'
      owner: "{{ main_user }}"

- name: Install bundler
  community.general.gem:
    name: bundler
    state: present

- name: Install smashing
  community.general.gem:
    name: smashing
    state: present

- name: Copy supervisord config to {{ supervisor_conf }}/{{ project_slug }}-backend.conf
  template:
    src: backend-supervisor.conf.j2
    dest: "{{ supervisor_conf }}/{{ project_slug }}-backend.conf"
    owner: root
    group: root
    mode: 0644

- name: Install {{ project_slug }}-backend supervisor
  supervisorctl:
    name: "{{ project_slug }}-backend"
    state: present

- name: Generate backend /etc/ssh/ RSA host key
  command: "ssh-keygen -q -t ed25519 -a 100 -f {{ backend_identity_file_path }} -C \"\" -N \"\""
  become_user: "{{ main_user }}"
  args:
    creates: "{{ backend_identity_file_path }}"
  register: backend_new_ssh_key

- name: WARNING ABOUT new ssh key
  debug:
    msg: |
      IMPORTANT REMINDER

      A new ssh key has been generated at {{ backend_identity_file_path }}
      - it should be added to the project deploy keys in Gitlab/Github
      so that we can clone it.
  when: backend_new_ssh_key.changed

- name: Get new ssh key contents
  command: "cat {{ backend_identity_file_path }}.pub"
  register: backend_command_output
  when: backend_new_ssh_key.changed

- name: Print ssh key to console
  debug:
    msg: "{{ backend_command_output.stdout }}"
  when: backend_new_ssh_key.changed

- name: get latest code
  git:
    repo: '{{ backend_repo }}'
    dest: "{{ backend_path }}"
    key_file: "{{ backend_identity_file_path }}"
    force: true
    version: "{{ backend_branch }}"
    accept_hostkey: true
  become_user: "{{ main_user }}"
  register: clonecode

- name: Restart {{ project_slug }} supervisor
  supervisorctl:
    name: "{{ project_slug }}-backend"
    state: restarted
  when: clonecode.changed or force_update is defined
