backend_application_port: 8035  # must be unique for each project on the same server
environment_suffix: ""
project_slug: "{{ base_project_slug }}{{ environment_suffix }}"

public_hostnames:
  - app.{{ project_slug }}.com
  - "{{ project_slug }}.{{ organization_slug }}.fr"
project_dir: "{{project_base_dir}}{{ environment_suffix }}"
backend_static_path: "{{ project_dir }}/backend_static"

frontend_branch: main
backend_branch: main

environment_name: production
