- name: Remove default nginx config
  file:
    state: absent
    dest: /etc/nginx/sites-enabled/default
  notify:
    - reload nginx

- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/{{ project_slug }}
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
